### ISSUE TITLE
Auto calibration failure leads to undefined mm-pixel ratio

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-ver2#12]
If auto calibration for mm-pixel ratio of either up or down camera fails, the calibration values are all set to 0.

This makes repeating the auto calibration impossible - also optical homing or fiducial detection will no longer work.

I suggest that software should fall back to previous values if auto calib fails.

**Comment by thethereza** [comment]
just type in some reasonable values and try again.  like 1mm or something. more importantly, how is it failing?

**Comment by mrandt** [comment]
That's what I do - just type a value and then it usually works again.

Reasons why it may fail are:
- no homing mark in field of view
- visual filters not configured correctly
- needle not attached

Suggestion: If auto calibration does not detect a homing mark (down cam) or needle (up cam) or fails for other reason, the old values could be kept instead of overwriting them with zero.

**Comment by thethereza** [comment]
fixed in next release.

**Comment by mrandt** [comment]
Thanks, I will retest once available.

**Comment by mrandt** [comment]
Fixed in SVN Release 18. Thanks!
