### ISSUE TITLE
Missing "reset" function on tapes

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-ver2#16]
There used to be a button to "reset" a tape position. It would set next component to 1 again and invalidate Z-level calibration for pickup and place.

We also used to have a button "reset all tapes" which executed said function on all tapes.

Both were helpful when starting a new job after resupplying tapes.

Is there equivalent function that I did not find or understand? Otherwise we should add the functions again.

**Comment by thethereza** [comment]
they're there someplace.  i think they are in drop down context menus that will be released soon.  getting rid of a lot of buttons to further clean up real-estate that way.

**Comment by mrandt** [comment]
Found them in top menu - fair enough. Maybe my UX design "excercise" in the forum leads to a revised UI in the longterm, so I guess we can handle it there :wink:

So I will close this for now.

**Comment by thethereza** [comment]
i don't want to see emails - how do i disable them?

**Comment by mrandt** [comment]
Hi Reza,

sign into GitHub, then go here:
https://github.com/settings/notifications

Cheers
Malte

Am 14.07.2015 um 22:50 schrieb thethereza:
