### ISSUE TITLE
Suggest to remove "Set Location" from main menu

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-ver2#6]
I would remove that menu alltogether.

Despite the yellow color it is still too dangerous - I accidentally overwrote the locations several times already... ;-)

**Comment by thethereza** [comment]
yeah, probably a good idea. though the color should be orange.

**Comment by mrandt** [comment]
Ok, yellowish orange :smile: But still not enough warning sign for me not to click, apparently...

**Comment by mrandt** [comment]
SVN Release 18 has the "Set Location" menu removed. I am more than happy to set locations in the corresponding tab - no more accidental overwrites :+1: 

Closing, thanks!
