### ISSUE TITLE
Do not move machine to "Park" position when closing application

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-ver2#7]
This feature is dangerous. Assume I open the application, do not home the machine but close the program again right away.

Happened to me during testing while the Gantry was somewhere in the middle... It moved unexpectedly and Y axis crashed hard into the frame and destroyed the limit switch.

**Comment by mrandt** [comment]
If we had a feature as described in #8 this would not be a problem. Machine would only allow movement to park position after it has been homed before.

**Comment by thethereza** [comment]
good idea. will track if homed on startup.

**Comment by thethereza** [comment]
implemented. not sure how to 'close' this

**Comment by mrandt** [comment]
@thethereza see my comments on related #8 - can you explain what exactly you have implemented now? Thanks!

**Comment by mrandt** [comment]
@thethereza Regarding closing issues: That can be done by Juha (repository owner) or the person who opened the issue in the first place.

I suggest that @jkuusama adds labels to issues (bug, enhancement, wontfix and a label "implemented") to categorize them. Allows filtering once we have a larger list.

Once someone fixed an issue, a comment should be added to issue stating which release (SVN) or commit (git) the code is in and maybe quick explanation. After successful retest, the issue should be closed.

**Comment by mrandt** [comment]
Fixed in SVN Release 18. Machine now only "parks" if "Home" is green - closing.
